### ISSUE TITLE
Create localization tests

### ISSUE THREAD

**Issue by jwillinghalpern** [jwillinghalpern/fm_rainbow_log#17]
These should read from actual log files (they can be doctored) and test things like:

- different line types are correctly parsed into their corresponding enum variants: Success, Warning, Error etc
- false positives. Some of the warning detection logic uses "contains()", which incorrectly label lines as warnings if, say, a script name or field contains that phrase.

**Comment by DavidWikstrom** [comment]
I was trying to come up with some false positives, but I so far I haven't really succeeded. Maybe this is less of a problem than I thought (at least in practice).

```
2023-05-04 19:12:49.162 +0200 FalsePositives 0 La rubrique “ya existe” a été importée sous le nom “ya existe 2” car une rubrique nommée “ya existe” existe déjà.
```

This is obviously running FileMaker in French with a field in Spanish. Since Spanish is before French in the order of checks,  this gets flagged as a warning for the wrong reason, but if it hadn't been recognized as a warning by FileMaker, the "ya existe" wouldn't have been part of the Import.log anyway.

Since the code is just checking the message part, not the whole line, calling a file "ya existe" doesn't make a false positive.

**Comment by jwillinghalpern** [comment]
Very interesting. I wouldn't have thought of that chicken-egg nuance if you hadn't checked.

**Comment by jwillinghalpern** [comment]
Here's one false positive. If you use the Scripts > Import... menu item instead of importing from clipboard:

<img width="797" alt="Screenshot 2023-05-04 at 12 07 00 PM" src="https://user-images.githubusercontent.com/16845102/236304375-26e2d3d1-553c-43eb-b721-6dffc28bb2cf.png">

**Comment by jwillinghalpern** [comment]
@DavidWikstrom the japanese Import.log you provided has this in it:
<img width="1361" alt="Screenshot 2023-05-04 at 1 03 52 PM" src="https://user-images.githubusercontent.com/16845102/236317117-a33581f0-9baf-4b7c-ba58-cdcf1ee53d4f.png">

Did that happen naturally? That looks abnormal.

**Comment by DavidWikstrom** [comment]
Nope, I pasted the wrong language by mistake and was sloppy cleaning up!

**Comment by jwillinghalpern** [comment]
Ok that's good news!
