### ISSUE TITLE
Utility App?

### ISSUE THREAD

**Issue by DanShockley** [jwillinghalpern/fm_rainbow_log#44]
Not sure if it would make sense to include this IN this project, but I threw together a little AppleScript applet, "fmrl on This Folder.app". You can toss it into the same folder where a FileMaker "Import.log" file resides, and it will fire up fmrl in a new Terminal window, monitoring that folder's Import.log. 
Note that the first time you open the applet on your Mac, it will ask for permission to automate the Terminal app. After you've authorized one applet, you can copy that applet to other folders and it shouldn't need to ask again. 
I'm attaching it here, Josh, in case you think it would be useful. Alternatively, if you'd like to link to it but not include it, I could make a mini github project for it and you could link to that. 
[fmrl on This Folder.app-2023-09-07-1155.zip](https://github.com/jwillinghalpern/fm_rainbow_log/files/12551200/fmrl.on.This.Folder.app-2023-09-07-1155.zip)

**Comment by jwillinghalpern** [comment]
@DanShockley this is really cool tool idea since you can just copy it into local projects and boom, easy log watcher.

FYI I got a weird output when I tried it in my Downloads folder, but it worked when i copied it into a nested folder.
<img width="638" alt="Screenshot 2023-09-07 at 9 11 25 AM" src="https://github.com/jwillinghalpern/fm_rainbow_log/assets/16845102/b6ef94b4-4f54-431f-b8f3-f2a39ece88df">

Is that maybe a bug or something weird about my setup?

> Alternatively, if you'd like to link to it but not include it, I could make a mini github project for it and you could link to that.
I think it makes more sense as a separate repo with a link in fmrl's README. That's primarily because of how fmrl is currently installed, either by `cargo` or pre-compiled binary from the Releases tab. It would be harder to go find this applet after installation via `cargo`, e.g.

What do you think? If you create a separate repo, would it make sense to include the source code too, so users can vet and open related issues directly?

**Comment by DanShockley** [comment]
Sounds like a good idea. 
I put together a fairly bare-bones repo, at https://github.com/DanShockley/FM_Rainbow_Log-Opener-applet
It's got the source code (a single AppleScript file), plus a zipped compiled applet for folks who don't want to have to "Save As…" in Script Editor. 

I think firing it up in the Downloads folder runs into some interesting macOS security thing, since I see "AppTranslocation" in that error message you got. Something about downloaded apps running directly in the Downloads folder, I think. I added a suggestion to the README that users move it out of the Downloads folder before they first open it, in case that helps.

**Comment by jwillinghalpern** [comment]
It is done! The readme has a section for this below `Basic Usage`. Thanks for making that, I'll use it too.
